/* Live integration checks plus isolated provider-failure and race scenarios.
   Run with the app served at WEATHER_TEST_URL (default http://127.0.0.1:8000).
   Fixtures below are used only in tests and never shipped in the application. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const url=process.env.WEATHER_TEST_URL || 'http://127.0.0.1:8000';
const artifacts=path.join(__dirname,'../artifacts');
fs.mkdirSync(artifacts,{recursive:true});
(async()=>{
 const options=process.env.WEATHER_BROWSER ? {executablePath:process.env.WEATHER_BROWSER} : process.platform==='win32' ? {channel:'chrome'} : {};
 const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader'],...options});
 try {
  const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
  await context.addInitScript(()=>localStorage.setItem('pimx.weather.lang','"en"'));
  const page=await context.newPage();const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  const source=page.waitForResponse(r=>r.url().startsWith('https://api.open-meteo.com/v1/forecast?')&&r.url().includes('hourly='));
  await page.goto(url,{waitUntil:'domcontentloaded'});
  const response=await source;assert.equal(response.status(),200);
  const raw=await response.json();
  await page.waitForFunction(()=>document.querySelector('#overview').getAttribute('aria-busy')==='false');
  assert.equal(await page.locator('#currentTemp').innerText(),new Intl.NumberFormat('en-GB',{maximumFractionDigits:0}).format(raw.current.temperature_2m));
  assert.equal(await page.locator('.forecast-day').count(),7);
  assert.equal(await page.locator('#loadHistory').isEnabled(),true);
  console.log('PASS live provider data matches the visible temperature');
  await page.locator('#unitF').click();
  assert.equal(await page.locator('#currentTemp').innerText(),new Intl.NumberFormat('en-GB',{maximumFractionDigits:0}).format(raw.current.temperature_2m*9/5+32));
  await page.locator('#unitC').click();
  await page.locator('[data-days="14"]').click();assert.equal(await page.locator('.forecast-day').count(),14);
  await page.locator('[data-day="3"]').click();assert.equal(await page.locator('[data-day="3"]').getAttribute('aria-pressed'),'true');
  const selected=await page.evaluate(weather=>WeatherData.viewContext(weather,3,null),raw);
  assert.equal(await page.locator('#currentTemp').innerText(),new Intl.NumberFormat('en-GB',{maximumFractionDigits:0}).format(raw.hourly.temperature_2m[selected.hour]));
  const lunar=await page.evaluate(context=>SkyData.snapshot(context.epoch,context.start,context.end,35.6892,51.389).moon,selected);
  assert.equal(await page.locator('#moonIlluminationDetail').innerText(),new Intl.NumberFormat('en-GB',{maximumFractionDigits:1}).format(lunar.illumination*100)+'%');
  const oldSunAngle=await page.locator('#sunAltitudeDetail').innerText();
  await page.locator('#solarSystemHour').evaluate(e=>{e.value=1080;e.dispatchEvent(new Event('input',{bubbles:true}));});
  assert.notEqual(await page.locator('#sunAltitudeDetail').innerText(),oldSunAngle);
  assert.match(await page.locator('#solarSystemHourDisplay').innerText(),/18:00/);
  assert.equal(await page.locator('[data-metric="surfacePressure"] .metric-value').innerText(),new Intl.NumberFormat('en-GB',{maximumFractionDigits:0}).format(raw.hourly.surface_pressure[selected.hour+6])+'hPa');
  await page.locator('#astronomy').scrollIntoViewIfNeeded();await page.locator('#astronomy').screenshot({path:path.join(artifacts,'observatory.png'),animations:'disabled'});
  await page.locator('#solarSystem').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>document.querySelector('#solarCanvas').dataset.renderer==='webgl',{timeout:20000});
  await page.waitForSelector('.planet-label');assert.equal(await page.locator('.planet-label').count(),8);
  await page.locator('[data-planet="Saturn"]').first().click();assert.equal(await page.locator('[data-planet-coordinates="Saturn"]').count(),1);
  await page.waitForFunction(()=>document.querySelector('#solarCanvas').dataset.epoch);
  assert.equal(Number(await page.locator('#solarCanvas').getAttribute('data-epoch')),selected.start+1080*60);
  await page.locator('#timePlay').click();await page.waitForFunction(()=>document.querySelector('#solarSystemHourDisplay').textContent==='19:00',{timeout:4000});await page.locator('#timePlay').click();
  assert.equal(Number(await page.locator('#solarCanvas').getAttribute('data-epoch')),selected.start+1140*60);
  await page.locator('#solarSystemHour').evaluate(e=>{e.value=1080;e.dispatchEvent(new Event('input',{bubbles:true}));});
  await page.locator('#zoomIn').click();await page.waitForFunction(()=>parseInt(document.querySelector('#zoomLevel').textContent.replace(/,/g,''))>100);
  await page.locator('#zoomReset').click();await page.locator('#solarMotion').click();assert.equal(await page.locator('#solarMotion').getAttribute('aria-pressed'),'false');
  await page.locator('#solarSystemSection').screenshot({path:path.join(artifacts,'solar-system.png'),animations:'disabled'});
  await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.locator('#solarSystemSection').screenshot({path:path.join(artifacts,'solar-mobile.png'),animations:'disabled'});
  await page.setViewportSize({width:1440,height:1000});await page.locator('#resetToNow').click();
  console.log('PASS selected date/hour synchronizes weather, lunar phase, solar angles, metrics and real WebGL planetary coordinates');
  await page.locator('[data-mode="precipitation_probability"]').click();assert.equal(await page.locator('#hourlyChart svg').count(),1);
  await page.locator('[data-mode="wind_speed_10m"]').click();await page.locator('[data-mode="temperature_2m"]').click();
  console.log('PASS unit conversion, 14-day selector, day detail and chart modes');
  await page.locator('#saveCityButton').click();assert.equal(await page.locator('.saved-city').count(),1);
  const downloadPromise=page.waitForEvent('download');await page.locator('#exportButton').click();const download=await downloadPromise;
  const csv=fs.readFileSync(await download.path(),'utf8');assert.ok(csv.includes('utc_timestamp'));assert.ok(csv.includes('temperature_2m [°C]'));assert.equal(csv.split('\r\n').length,raw.hourly.time.length+1);
  console.log('PASS saved location and real-data CSV export');
  await page.locator('#dataInfoButton').click();assert.equal(await page.locator('#sourceDialog').isVisible(),true);await page.keyboard.press('Escape');
  await page.locator('#themeButton').click();assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('light')),true);await page.locator('#themeButton').click();
  await page.locator('#languageButton').click();assert.equal(await page.locator('html').getAttribute('dir'),'rtl');
  await page.locator('[data-days="7"]').click();
  await page.screenshot({path:path.join(artifacts,'desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:path.join(artifacts,'mobile.png'),fullPage:true});
  await page.setViewportSize({width:360,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.setViewportSize({width:1440,height:1000});await page.locator('#languageButton').click();
  console.log('PASS bilingual RTL, theme, source dialog and mobile layout');
  await page.locator('#loadHistory').click();
  await page.waitForFunction(()=>!!document.querySelector('.history-stats') || !!document.querySelector('[data-action=history]'),{timeout:25000});
  assert.equal(await page.locator('.history-stats').count(),1);
  console.log('PASS live historical archive');
  await page.locator('#map-section').scrollIntoViewIfNeeded();await page.waitForSelector('.leaflet-container');
  await page.locator('#radarToggle').click();
  await page.waitForFunction(()=>!document.querySelector('#radarToggle').disabled,{timeout:25000});
  assert.equal(await page.locator('#radarToggle').getAttribute('aria-pressed'),'true');
  assert.equal(await page.locator('#radarSlider').isEnabled(),true);
  await page.locator('#radarToggle').click();
  console.log('PASS map initialization and live radar metadata');
  await page.locator('#languageButton').click();await page.locator('#overview').scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(artifacts,'desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(artifacts,'mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});await page.locator('#languageButton').click();
  await page.locator('#searchInput').fill('London');
  await page.waitForSelector('.search-result',{timeout:25000});await page.locator('.search-result').first().click();
  await page.waitForFunction(()=>document.querySelector('#overview').getAttribute('aria-busy')==='false');
  assert.match(await page.locator('#placeName').innerText(),/London/);assert.match(await page.locator('#localClock').innerText(),/Europe\/London/);
  await page.locator('#saveCityButton').click();assert.equal(await page.locator('.saved-city').count(),2);
  await page.locator('.city-remove').first().click();assert.equal(await page.locator('.saved-city').count(),1);
  console.log('PASS geocoding, city timezone, save and remove');
  await page.route('https://api.open-meteo.com/**',route=>route.abort('failed'));
  const oldTemp=await page.locator('#currentTemp').innerText();await page.locator('#refreshButton').click();
  await page.waitForFunction(()=>document.querySelector('#overview').getAttribute('aria-busy')==='false');
  assert.equal(await page.locator('#currentTemp').innerText(),oldTemp);assert.match(await page.locator('#statusBanner').innerText(),/Previous data/);
  await page.locator('[data-quick="2"]').click();await page.waitForFunction(()=>document.querySelector('#overview').getAttribute('aria-busy')==='false');
  assert.equal(await page.locator('#currentTemp').innerText(),'—');assert.equal(await page.locator('.forecast-day').count(),0);
  console.log('PASS failed refresh labels retained data; failed city switch clears all old weather');
  assert.deepEqual(errors,[]);
  await context.close();

  // Delay one city's response while another finishes; only the newest may render.
  const isolated=await browser.newContext();await isolated.addInitScript(()=>localStorage.setItem('pimx.weather.lang','"en"'));
  const race=await isolated.newPage();
  await race.route('https://api.open-meteo.com/**',async route=>{
   const u=new URL(route.request().url()),lat=Number(u.searchParams.get('latitude'));
   if(lat===35.6892)await new Promise(resolve=>setTimeout(resolve,500));
   const now=Math.floor(Date.now()/3600000)*3600;
   const fixture={timezone:lat===35.6892?'Asia/Tehran':'Asia/Dubai',latitude:lat,longitude:55,elevation:1,current:{time:now,temperature_2m:lat===35.6892?12:31,is_day:1,weather_code:0},hourly:{time:[now,now+3600],temperature_2m:[null,31],precipitation_probability:[null,0],weather_code:[0,0],is_day:[1,1]},daily:{time:[now],temperature_2m_max:[31],temperature_2m_min:[21],weather_code:[0]}};
   await route.fulfill({json:fixture}).catch(()=>{});
  });
  await race.route('https://air-quality-api.open-meteo.com/**',route=>route.abort());
  await race.goto(url,{waitUntil:'domcontentloaded'});await race.locator('[data-quick="2"]').click();
  await race.waitForFunction(()=>document.querySelector('#overview').getAttribute('aria-busy')==='false');
  await race.waitForTimeout(700);assert.equal(await race.locator('#placeName').innerText(),'Dubai');assert.equal(await race.locator('#currentTemp').innerText(),'31');
  assert.match(await race.locator('#airContent').innerText(),/unavailable/);
  assert.equal(await race.locator('.hour-card strong').first().innerText(),'—');
  assert.equal(await race.locator('[data-metric="uv"] .metric-value').innerText(),'—');
  await race.setViewportSize({width:390,height:844});assert.equal(await race.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  console.log('PASS stale responses cannot overwrite a new city; missing values remain missing; AQ failure is independent');
  await race.locator('#solarSystem').scrollIntoViewIfNeeded();await race.waitForFunction(()=>document.querySelector('#solarCanvas').dataset.renderer);
  assert.equal(await race.locator('.planet-table tbody tr').count(),8);
  if(await race.locator('#solarCanvas').getAttribute('data-renderer')==='webgl'){
    await race.locator('#solarCanvas canvas').evaluate(canvas=>canvas.getContext('webgl2').getExtension('WEBGL_lose_context').loseContext());
    await race.waitForFunction(()=>document.querySelector('#solarCanvas').dataset.renderer==='fallback');
    assert.equal(await race.locator('[data-solar-body]').count(),8);
    await race.locator('[data-planet="Mars"]').first().click();
    assert.match(await race.locator('#planetInfoBox').innerText(),/Mars/);
    console.log('PASS a lost WebGL context keeps the celestial data and planet controls working');
  }
  await isolated.close();
  const fallbackContext=await browser.newContext();await fallbackContext.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(type.startsWith('webgl'))return null;return original.call(this,type,...args);};});
  const fallbackPage=await fallbackContext.newPage();await fallbackPage.route('https://api.open-meteo.com/**',route=>route.fulfill({json:raw}));await fallbackPage.route('https://air-quality-api.open-meteo.com/**',route=>route.abort());
  await fallbackPage.goto(url,{waitUntil:'domcontentloaded'});await fallbackPage.locator('#solarSystem').scrollIntoViewIfNeeded();await fallbackPage.waitForFunction(()=>document.querySelector('#solarCanvas').dataset.renderer==='fallback');
  assert.equal(await fallbackPage.locator('[data-solar-body]').count(),8);assert.equal(await fallbackPage.locator('#moonAgeDetail').count(),1);
  await fallbackContext.close();console.log('PASS WebGL fallback preserves every planet and all celestial data');console.log('ALL BROWSER CHECKS PASSED');
 } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
